version: 2.1

orbs:
  maven: circleci/maven@1.0.3
  slack: circleci/slack@4.0.2

jobs:
  notify-slack:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          color: "#42e2f4"
          message: "The build is passing!!"

workflows:
  maven_test:
    jobs:
      - maven/test
      - notify-slack

